spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mentorhub?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}      # Gemini API 호출에 사용하는 Google API Key
        project-id: ${GCP_PROJECT_ID}  # Google Cloud Project ID
        location: us-central1          # Gemini API 실행 리전 (전 세계 공통 권장값)
        chat:
          model: gemini-3-pro-preview      # 사용할 Gemini 모델
          options:
            temperature: 0.5           # 응답 창의성 조절 (0.0=정확 / 1.0=창의적, 0.5는 균형형)
        embedding:
          api-key: ${GEMINI_API_KEY}
          options:
            model: text-embedding-004  # Gemini embedding 모델
    vectorstore:
      qdrant:
        host: localhost
        port: 6333
        api-key:
        collection-name: mentee_writing_vectors
        use-tls: false
        initialize-schema: false